module.exports = {
  up: (queryInterface) => {
    return queryInterface.bulkInsert("subcategories", [
      {
        name: "Rent/Mortgage",
        isUserDefinedSubcategory: false,
        isSubcategoryActive: true,
        categoryId: 1,
        userId: null,
        color: "#808080",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Electricity",
        isUserDefinedSubcategory: false,
        isSubcategoryActive: true,
        categoryId: 1,
        userId: null,
        color: "#FFFF00",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Gas",
        isUserDefinedSubcategory: false,
        isSubcategoryActive: true,
        categoryId: 1,
        userId: null,
        color: "#00FF00",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Internet",
        isUserDefinedSubcategory: false,
        isSubcategoryActive: true,
        categoryId: 1,
        userId: null,
        color: "#FF00FF",
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        name: "Vehicle loan/lease",
        isUserDefinedSubcategory: false,
        isSubcategoryActive: true,
        categoryId: 2,
        userId: null,
        color: "#0000FF",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Gasoline",
        isUserDefinedSubcategory: false,
        isSubcategoryActive: true,
        categoryId: 2,
        userId: null,
        color: "#FFBF00",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Public transportation costs",
        isUserDefinedSubcategory: false,
        isSubcategoryActive: true,
        categoryId: 2,
        userId: null,
        color: "#FF7F50",
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        name: "Groceries",
        isUserDefinedSubcategory: false,
        isSubcategoryActive: true,
        categoryId: 3,
        userId: null,
        color: "#9FE2BF",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Dining out",
        isUserDefinedSubcategory: false,
        isSubcategoryActive: true,
        categoryId: 3,
        userId: null,
        color: "#40E0D0",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Coffee and beverages",
        isUserDefinedSubcategory: false,
        isSubcategoryActive: true,
        categoryId: 3,
        userId: null,
        color: "#6495ED",
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        name: "Health",
        isUserDefinedSubcategory: false,
        isSubcategoryActive: true,
        categoryId: 4,
        userId: null,
        color: "#CCCCFF",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Life",
        isUserDefinedSubcategory: false,
        isSubcategoryActive: true,
        categoryId: 4,
        userId: null,
        color: "#454545",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Travel insurance",
        isUserDefinedSubcategory: false,
        isSubcategoryActive: true,
        categoryId: 4,
        userId: null,
        color: "#999999",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },
  down: (queryInterface) => {
    return queryInterface.bulkDelete("subcategories", null, {});
  },
};
